name: Update README with Python files

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Python files and update README
        run: |
          # Find all .py files in the repository
          FILES=$(find . -type f -name "*.py" | sort)
          # Remove the leading './' from the filenames
          FILES=$(echo "$FILES" | sed 's/^\.\///')
          
          # Prepare bullet points for README
          BULLET_POINTS="# Solutions"
          for FILE in $FILES; do
            BULLET_POINTS="$BULLET_POINTS- $FILE\n"
          done
          
          # Update README with bullet points
          echo -e "$BULLET_POINTS" > README.md

      - name: Commit changes
        run: |
          git config --global user.name 'Videet Parekh'
          git config --global user.email 'videetparekh0047@gmail.com'
          git add README.md
          git commit -m "Update README with Python files" || echo "No changes to commit"
          git push
